db.hostname=localhost
db.password=administrator99
db.port=1521
db.servicename=XEPDB1
db.username=APEX_PUBLIC_USER
plsql.gateway.add=true
rest.services.apex.add=true
rest.services.ords.add=true
schema.tablespace.default=SYSAUX
schema.tablespace.temp=TEMP
standalone.http.port=8080
standalone.mode=true
standalone.static.images=/opt/oracle/ords/images
standalone.use.https=false
user.apex.listener.password=administrator99
sys.user=SYS
sys.password=administrator99
user.apex.restpublic.password=administrator99
user.public.password=administrator99
user.tablespace.default=SYSAUX
user.tablespace.temp=TEMP
